# Product entity routing definition

entity.product_entity.canonical:
  route_name: entity.product_entity.canonical
  base_route: entity.product_entity.canonical
  title: 'View'

entity.product_entity.edit_form:
  route_name: entity.product_entity.edit_form
  base_route: entity.product_entity.canonical
  title: 'Edit'

entity.product_entity.version_history:
  route_name: entity.product_entity.version_history
  base_route: entity.product_entity.canonical
  title: 'Revisions'

entity.product_entity.delete_form:
  route_name:  entity.product_entity.delete_form
  base_route:  entity.product_entity.canonical
  title: Delete
  weight: 10
