entity.product_entity.add_form:
  route_name: entity.product_entity.add_page
  title: 'Add Product entity'
  appears_on:
    - entity.product_entity.collection
entity.product_entity_type.add_form:
  route_name: entity.product_entity_type.add_form
  title: 'Add Product entity type'
  appears_on:
    - entity.product_entity_type.collection
